// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("NetConsole.WebApi")]
[assembly: AssemblyProductAttribute("NetConsole.WebApi")]
[assembly: AssemblyDescriptionAttribute("NetConsole.WebApi is a package that it provides a way to access commands by using a sort of RPC-like API interaction.")]
[assembly: AssemblyVersionAttribute("0.1.0")]
[assembly: AssemblyFileVersionAttribute("0.1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.1.0";
    }
}
